import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.gray80003,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.red500,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10.h),
          ),
          shadowColor: colorScheme.primary,
          elevation: 10,
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.whiteA70001,
            width: 2.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.gray90006,
          fontSize: 18.fSize,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.primary.withOpacity(0.6),
          fontSize: 15.fSize,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.blueGray100.withOpacity(0.64),
          fontSize: 10.fSize,
          fontFamily: 'Lexend Deca',
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 48.fSize,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: FontWeight.w700,
        ),
        headlineLarge: TextStyle(
          color: appTheme.whiteA70001,
          fontSize: 30.fSize,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: FontWeight.w700,
        ),
        headlineMedium: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 28.fSize,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: appTheme.whiteA70001,
          fontSize: 24.fSize,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: FontWeight.w700,
        ),
        labelLarge: TextStyle(
          color: appTheme.gray90005,
          fontSize: 12.fSize,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: colorScheme.onErrorContainer,
          fontSize: 22.fSize,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 18.fSize,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: appTheme.blueGray900,
          fontSize: 15.fSize,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: FontWeight.w500,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0X3F000000),
    primaryContainer: Color(0XFF1B1919),
    secondaryContainer: Color(0XCC000000),

    // Error colors
    errorContainer: Color(0XFFD1817F),
    onError: Color(0XFFEAEAEA),
    onErrorContainer: Color(0XFF181717),

    // On colors(text colors)
    onPrimary: Color(0XFF2C2A2A),
    onPrimaryContainer: Color(0XFFABABAB),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF0A0A0A);

  // Blue
  Color get blueA100 => Color(0XFF8EB4FF);

  // BlueGray
  Color get blueGray100 => Color(0XFFD6D6D6);
  Color get blueGray10001 => Color(0XFFD0D0D0);
  Color get blueGray10002 => Color(0XFFCBCBCB);
  Color get blueGray10003 => Color(0XFFD7D7D7);
  Color get blueGray10004 => Color(0XFFD3D6D5);
  Color get blueGray10005 => Color(0XFFD9D9D9);
  Color get blueGray10006 => Color(0XFFCFCFCF);
  Color get blueGray400 => Color(0XFF8B8B8B);
  Color get blueGray50 => Color(0XFFF1F1F1);
  Color get blueGray700 => Color(0XFF515151);
  Color get blueGray900 => Color(0XFF373737);
  Color get blueGray90001 => Color(0XFF363636);
  Color get blueGray90002 => Color(0XFF333333);

  // DeepOrange
  Color get deepOrange100 => Color(0XFFEAB9B7);
  Color get deepOrange10001 => Color(0XFFFAC6C3);
  Color get deepOrange10002 => Color(0XFFF6B5B5);
  Color get deepOrange200 => Color(0XFFFFB1AD);
  Color get deepOrange50 => Color(0XFFF8E4E2);
  Color get deepOrangeA400 => Color(0XFFFF1414);

  // DeepPurple
  Color get deepPurple100 => Color(0XFFC7BBEC);

  // Gray
  Color get gray100 => Color(0XFFF2F7F4);
  Color get gray200 => Color(0XFFE7E7E7);
  Color get gray400 => Color(0XFFD2A8AF);
  Color get gray40001 => Color(0XFFB0B0B0);
  Color get gray40002 => Color(0XFFB2B2B2);
  Color get gray40003 => Color(0XFFC9C9C9);
  Color get gray40004 => Color(0XFFBDBDBD);
  Color get gray40005 => Color(0XFFB3B3B3);
  Color get gray40006 => Color(0XFFC2C2C2);
  Color get gray40007 => Color(0XFFB9B9B9);
  Color get gray50 => Color(0XFFFAFAFA);
  Color get gray500 => Color(0XFFADADAD);
  Color get gray600 => Color(0XFF6D6D6D);
  Color get gray60001 => Color(0XFF737373);
  Color get gray60002 => Color(0XFF6F6F6F);
  Color get gray700 => Color(0XFF614469);
  Color get gray70001 => Color(0XFF626563);
  Color get gray70002 => Color(0XFF5C5C5C);
  Color get gray70003 => Color(0XFF614369);
  Color get gray70004 => Color(0XFF686666);
  Color get gray700A2 => Color(0XA2545D5A);
  Color get gray800 => Color(0XFF484141);
  Color get gray80001 => Color(0XFF444444);
  Color get gray80002 => Color(0XFF505050);
  Color get gray80003 => Color(0XFF3A3A3A);
  Color get gray900 => Color(0XFF1B1B1B);
  Color get gray90001 => Color(0XFF201D1D);
  Color get gray90002 => Color(0XFF111111);
  Color get gray90003 => Color(0XFF131313);
  Color get gray90004 => Color(0XFF0C1C16);
  Color get gray90005 => Color(0XFF1F1F1F);
  Color get gray90006 => Color(0XFF292929);

  // GrayEd
  Color get gray50Ed => Color(0XEDF9F9F9);

  // Indigo
  Color get indigo100 => Color(0XFFBBD4EC);

  // Lime
  Color get lime100 => Color(0XFFEBECBB);

  // Pink
  Color get pink100 => Color(0XFFECBBC0);

  // Purple
  Color get purple200 => Color(0XFFCAABD2);
  Color get purple50 => Color(0XFFF0DDFF);

  // Red
  Color get red300 => Color(0XFFB87279);
  Color get red500 => Color(0XFFFF3C3C);
  Color get redA700 => Color(0XFFF70000);

  // White
  Color get whiteA700 => Color(0XFFFFFEFD);
  Color get whiteA70001 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
